### ISSUE TITLE
dotnet issue

### ISSUE THREAD

**Issue by prashast1310** [haydenmc/SeatChecker#1]
"dotnet restore" gives an error that no project file exists.

<img width="1440" alt="screen shot 2017-03-31 at 4 07 06 pm" src="https://cloud.githubusercontent.com/assets/16947659/24567573/50e80bfe-162c-11e7-9b42-0a6b97fcfcf1.png">

**Comment by haydenmc** [comment]
This is because they changed project files in the latest dotnet tooling - try running `dotnet migrate`. I'll check this out and update when I get a chance. :)

**Comment by haydenmc** [comment]
Committed a change with the migration applied. Tested working. Thanks!
